---
- hosts: metal
  become: yes
  gather_facts: false
  vars:
    key: /etc/apt/keyrings/yarn-archive-keyring.gpg

  tasks:
  - name: Add Yarn Key
    apt_key:
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      keyring: "{{ key }}"
      state: present

  - name: Add Yarn Repo
    apt_repository:
      repo: "{{ item }}"
      state: present
      filename: yarn
    with_items:
      - deb [signed-by={{key }}] https://dl.yarnpkg.com/debian/ stable main

  - name: Install Yarn
    apt:
      name: yarn
      state: present